// Generated by scripts/write-angular-env.mjs. Do not commit credentials.
export const environment = {
  "supabaseUrl": "https://uawgpmhjuzpqskkswopd.supabase.co",
  "supabaseKey": "sb_publishable_GaMwg4_vhRqhuwksWvBkDA_tEkEaEJy"
} as const;
